### ISSUE TITLE
Question About Data Types

### ISSUE THREAD

**Issue by JBarsotti** [NDAR/nda-tools#32] opened 2021-07-13 18:42 UTC
Hello!

I hope you are well.

I am trying to upload a set of data but keep getting stuck on an error where my experiment ID is a string, when it should be an integer. Is this a new requirement for NDA uploads? In the past, the ID could be a string, or am I wrong?

Thank you for your time!

**Comment by gregmagdits** [comment] 2021-07-13 19:58
Hi, this looks more like an issue with the validation service rather than the nda-tools client. We have a Help Desk site to address user facing issues like this one. Can you create a ticket here? https://ndar.zendesk.com/ The ticket will be assigned to a developer if the issue is a technical one. We have full time staff dedicated to serving requests at the help desk, so issues reported there will be answered/addressed much more quickly than those that are posted here. 

In the meantime, we have begun looking at User reported issues listed on this github page, so we will push a fix for this issue if the problem is in fact inside the nda-tools codebase

**Comment by JBarsotti** [comment] 2021-07-13 20:07
Thank you so much for your quick response! I will create the ticket.

-- John

**Comment by petralenzini** [comment] 2021-07-13 22:37
Hi Greg, I'll make a ticket on ndar.zendesk.com, too, but on behalf of anyone else watching this repo, are you aware of a way of openly tracking Q and A via the helpdesk.  I mean, if I run into the same problem next month, do I have to open my own ticket, or is there a FAQ somewhere?

**Comment by gregmagdits** [comment] 2021-07-13 23:49
Hi Petra. I responded already on the HD ticket, but to reiterate, no I think we don't have anything like that in NDA yet. I just passed the idea along to the Help Desk team to see what they think - As you alluded to, it seems like an active Q ad A would make things easier for both the Help Desk and for users who want to try to answer their own questions.

**Comment by JBarsotti** [comment] 2021-07-14 12:55
Hi Greg and Petra,

I think that a Q and A would be awesome! Especially for someone like me who is a total novice when it comes to NDA.

-- John

**Closed** 2023-12-05 20:01 UTC
